### ISSUE TITLE
I'm curious about why "math.log" applies to denominator of time_signature message

### ISSUE THREAD

**Issue by zlind0** [Rainbow-Dreamer/musicpy#33]
I would like to develop a score analysis program and I would like to get time signature of each bar.
As a result, I find that time_signature is a message, which can be accessed by bar.other_messages, if the message is present. (If my way of accessing it is wrong, thanks for pointing out)

I have a minuet of 3/4.

Logic pro x gives the correct time signature.
![image](https://user-images.githubusercontent.com/19368368/144641878-254e8bb9-5bf8-40f2-b560-de29d0547b5d.png)

But in musicpy,

```
# musicpy.py:948
        current_message = time_signature(
            track=track_ind,
            time=time,
            numerator=message.numerator,
            denominator=int(math.log(message.denominator, 2)),  #this line
            clocks_per_tick=message.clocks_per_click,
            notes_per_quarter=message.notated_32nd_notes_per_beat)
```

Logarithm is applied to denominator, and if I print(msg.numerator, msg.denominator), I would get 3/2, which is different from expected.
I am curious about the logarithm. It should be intentional, but I don't quite understand. Thanks!

**Comment by Rainbow-Dreamer** [comment]
This is because musicpy uses mido to write out MIDI files, and the time_signature MIDI event in mido handles the denominator as the power of 2, you can refer to [here](https://mido.readthedocs.io/en/latest/meta_message_types.html#time-signature-0x58), and when reading MIDI files, musicpy uses midiutil which reads time_signature MIDI event's denominator as normal number, so I need to do a conversion of logarithm here, when writing the time_signature MIDI event the denominator in terms of power of 2 straight passes to the mido output function.
So here what you get is actually correct, here the actual denominator is `2 ** 2` which is 4. But yes, I think this can be improved, I can do conversion when writing out the time_signature MIDI events using mido instead, and you can access `(msg.numerator, msg.denominator)` as 3/4 when you have the time_signature messages.

**Comment by zlind0** [comment]
Thanks for the reply
