### ISSUE TITLE
Unable to set volume for tracks

### ISSUE THREAD

**Issue by vlin83** [Rainbow-Dreamer/musicpy#40]
When using this code from the github example, I was unable to set the 'volume' argument for tracks.
`new_piece = build(track(A1, instrument='Acoustic Grand Piano', start_time=0, channel=1, track_name='piano'))`
This works, as does setting `volume=` for new_piece.
`new_piece = build(track(A1, instrument='Acoustic Grand Piano', start_time=0, channel=1, track_name='piano',volume=40))`
The error came up when using the 'play' method
```
  File "C:\Users\vlign\AppData\Local\Programs\Python\Python310\lib\site-packages\musicpy\musicpy.py", line 240, in play
    file = write(current_chord=current_chord,
  File "C:\Users\vlign\AppData\Local\Programs\Python\Python310\lib\site-packages\musicpy\musicpy.py", line 849, in write
    current_volume_channel = current_channel if each.channel is None else each.channel
AttributeError: 'int' object has no attribute 'channel'
```

**Comment by vlin83** [comment]
However, I found the `add_volume` method and was able to use this to set volume for notes of a chord individually within each track.

**Comment by Rainbow-Dreamer** [comment]
Hi, this error happens because for the `volume` argument of tracks and pieces, it is for MIDI CC messages to set the overall volume of a track, which is totally different from setting volume for each note in a chord. For track types, you can get the chord type of it by its `content` attribute, and set the volume of notes for the chord type. For the `volume` argument of the track type, you need to use `volume` class to initiate a volume type for the argument, for example,
```python
new_piece = build(track(A1, instrument='Acoustic Grand Piano', start_time=0, channel=1, track_name='piano',volume=volume(40)))
new_piece.play()
```
