### ISSUE TITLE
Any support for adding leading or trailing rests to chord objects? 

### ISSUE THREAD

**Issue by neldivad** [Rainbow-Dreamer/musicpy#73]
It is possible to fix the problem using start times during piece(), but certain segments of a chord sometimes don't take up the whole bar. 

```
chd.bars()
> 10.935 

chd2 = mp.rest(duration=0.065)
> chd2 = mp.rest(duration=0.065)

# expected behavior
chd3 = chd2 + chd
# chd3 = chd + chd2
chd3.bars() 
> 11.0 

# current 
chd3.bars()
> 10.935 # rest is ignored. 
```

The reason why I think this feature is critical is because midi files with trailing or leading rests will have their notes reindexed after importing as chord object and exporting as midi file. 

Current solution is 

```
chd3 = mp.piece([chd], start_times=[0.065]) # to apply leading rest 
chd3.bars()
> 11.0
```

One idea is to implement a chord method: 
```
def fill_bar(chord, leading=True):
    """ 
    Adjust chord to ensure it spans a whole number of bars
    """ 
    total_bars = chord.bars()
    remainder = total_bars % 1 

    if remainder == 0: 
        raise ValueError(f"Chord already spans {total_bars} bars.")
    
    if leading == True: 
        chord = mp.chord('', duration=remainder) + chord
    else:
        chord = chord + mp.chord('', duration=remainder)
    return chord

```

**Comment by neldivad** [comment]
Also, have another request for stacking chord objects in discussion tab. Thanks for the response yesterday

**Comment by Rainbow-Dreamer** [comment]
The reason why `chd3.bars()` gives you `10.935` is because the method `bars` takes an argument `start_time`, which is required when the chord itself has a start time and you want to count it as part of the length of chord, the method `bars` only calculates the actual length of the chord regardless of the `start_time` attribute of the chord, so the right usage of `bars` in this case is `chd3.bars(start_time=chd3.start_time)`, which gives you the correct result `11.0`
